[manager]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_dir_first = true
linemode = "size"
show_symlink = true

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix"}
]

# so when browsing a network mounted directory,
# yazi doesn't fetch the entire file to evaluate the mime-type.
[[plugin.prepend_fetchers]]
id   = "mime"
if   = "!mime"
name = "*"
run  = "mime-ext"
prio = "high"
