#! /bin/sh

# monitor-setup
bspc monitor eDP1 -d I II  IV V VI VII VIII  X
bspc monitor DP-3 -d I II  IV V VI VII VIII  X

bspc config border_width        2
bspc config window_gap          0
bspc config bottom_padding			25 # Polybar
# bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# https://www.reddit.com/r/bspwm/comments/92bddw/how_to_move_desktops_after_disconnecting_a_monitor/e54emyi/
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Brave-browser desktop='^2'
bspc rule -a Code - OSS desktop=^3
bspc rule -a vlc desktop=^4
bspc rule -a mpv desktop=^4
bspc rule -a TelegramDesktop desktop=^9 follow=off
bspc rule -a discord desktop=^10 follow=off

bspc rule -a Zathura state=tiled

##########################################
# Programs to run after initiating bspwm #
##########################################

# Wallpaper
feh --bg-fill $XDG_CONFIG_HOME/wallpaper.png

# Launch polybar
$HOME/.config/polybar/polybar_launch.sh

monitor-setup
