#! /bin/sh

# Launch polybar
$HOME/.config/polybar/polybar_launch.sh

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
# bspc monitor DP-3 -d I II III IV V VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave-browser desktop='^2'
bspc rule -a code-oss - OSS desktop=^3
bspc rule -a jetbrains-idea desktop=^3
bspc rule -a TelegramDesktop desktop=^9
bspc rule -a vlc desktop=^4

# Wallpaper
feh --bg-fill ~/Pictures/current-wallpaper.jpg
