#!/usr/bin/env python3
# coding=utf-8

import json
import requests
import os
import sys

API_URL = 'https://api.coinbase.com/v2/prices/BTC-USD/spot'
r = requests.get(API_URL)
data = json.loads(r.text)
price = float(data['data']['amount'])

displayFormat = '$ {}'
print(displayFormat.format(price))